### ISSUE TITLE
Standalone Binary for Decryption

### ISSUE THREAD

**Issue by tomk3003** [Leont/crypt-ecdh_es#1]
Just a question:
Is there any standalone (no Perl) executable available, that can decrypt the encrypted values?
I am working on a Mojolicious webserver that needs to store passwords but the users will not necessarily have Perl.
Asking them to just install a single binary would massively increase the acceptance.

**Comment by Leont** [comment]
>  Is there any standalone (no Perl) executable available, that can decrypt the encrypted values?

No there isn't, though it shouldn't be too hard to write such a thing.

What are you trying to achieve? Are you storing passwords to check, or are you storing credentials to log in to some external system?

**Comment by tomk3003** [comment]
I am storing encrytpted data (can be passwords). I do not need to check or use the data on the server side, just deliver the encrypted values to an authorized user. The user has the private key and should be able to decrypt the data. I don't want the data to be compromised when the server is. This should be the case when I only have the public key on the server.
It would be nice to have a small decryption program, that can be given to the user (most likely using Windows).

I just wanted to make sure, that this doesn't exist already before I start implementing it myself.

**Comment by Leont** [comment]
Yeah it doesn't already exist, but it should be easy enough to reimplement in a compiled language; the constructs I'm using are all fairly standard (though it would be easier with AES-GCM; support for that in Perl was poor when I wrote this module).

**Comment by tomk3003** [comment]
Implemented: see [ecdh_es](https://github.com/tomk3003/ecdh_es)
